version: "2.2"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.16
    depends_on:
      - elasticsearch
    volumes:
      - ../pipeline:/usr/share/logstash/pipeline
    networks:
      - elastic-stack
    environment:
      - xpack.monitoring.enabled=false
      - log.level=warn
      - config.reload.automatic=true
    init: true

  elasticsearch:
    init: true
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    networks:
      - elastic-stack
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    init: true
    image: docker.elastic.co/kibana/kibana:5.6.16
    depends_on:
      - elasticsearch
    ports: ["5601:5601"]
    networks:
      - elastic-stack
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.security.enabled=false

networks:
  elastic-stack:

volumes:
  esdata:
    driver: local
